### ISSUE TITLE
Laboratory Work #0

### ISSUE THREAD

**Issue by cupchik1** [OS-IS/ai202-bezugla#1]

**Comment by cupchik1** [comment]
![image](https://github.com/user-attachments/assets/eb954aef-c5b4-47e8-82be-006d68b115df)

**Comment by cupchik1** [comment]
![image](https://github.com/user-attachments/assets/aae2d002-e777-4dc6-b82b-61eacc083eb9)

**Comment by cupchik1** [comment]
![image](https://github.com/user-attachments/assets/9786194d-847e-4bf0-bf9e-70f1ac8c0137)

**Comment by cupchik1** [comment]
![image](https://github.com/user-attachments/assets/9baf5ab0-e9bc-44d4-a59c-5089edefed50)

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 5 балів.
Дякую
