### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [OS-IS/ai202-bezugla#3]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
2) Відомо, що Git-система контроля версій використовує поняття “гілка” (branch). 
Поясніть, будь ласка, як використання такої “гілки” 
може підвищити безпеку процесів створення програмного продукту?

**Comment by cupchik1** [comment]
Кожна гілка Git надає ізольований простір для роботи, тому працюючи в окремих гілках можна вільно тестувати зміни без ризику порушити працездатність основної (робочої) версії програмного продукту. Якщо щось піде не так, завжди можна повернутися до останньої стабільної версії, не відкочуючи зміни в проекті.

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 2 бали
